config/routes.rb
Studium::Application.routes.draw do
  get "/awaiting_confirmation",to: "users#dashboard",as: :confirm_user
  get "/dashboard",to: "users#dashboard",as: :user_root

  # Badge routes
  resources :badges,only: [:index]

  # User authentication
  devise_for :users,controllers: {registrations: "registrations", omniauth_callbacks: "users/omniauth_callbacks"}
  get "users/index"
  post "users/get_info", to:"users#get_user_data"

  # Profile Routes
  controller :profiles,path: "/users/:user_id/profile" do
    get action: "show", as: "user_profile"
    get :edit,as: "edit_user_profile"
    put action: :update
    post :increase_reputation
    post :update_status 
    get 'pull_pro_bar/:interval', action: :pull_pro_bar
    get "pull/:category_type_id", action: :pull
    get "pull_stacked/:category_type_id", action: :pull_stacked
  end

  # Category Type Routes
  resources :category_types,:question_types,only: [:new,:create,:index] 

  # Message routes
  resources :messages,only: [:index,:create] do
    get "/read/:message_id",action: :read,on: :collection,as: :read
    post :read_all,on: :collection
  end

  # Rooms_controller routes
  get "/search",to: "rooms#search_friend_all_results",as: "search_friends"
  resources :rooms,only: [:index,:create] do
    get :search_friend,on: :collection
  end
  controller :rooms,path: "/rooms",as: "room" do
    #get "/join/:room_title", action: "join", as: "join"
    get "/join/:room_id", action: "join", as: "join" 
    get :leave_room
    post :confirm
    post :show_question
    post :show_explanation
    post :room_list
    post :user_list
    post :ready
    post :kick
    post :show_histories
    post :invite
    post :chat_message
    post :show_current_user
    
    get "/review/:room_id", to: "rooms#review", as: "review"

  end

  #get_started page routes
  get "/getStarted", to: "get_started#index"

  # Admin-related routes
  get "admin", to: "homepage#admin",as: "admin_index"
  namespace "admin" do
    # Report
    get "reports/users"

    # Material namespace
    namespace "materials" do
      # Root page for material namespace
      root to: "base#index",as: "index"

      # Routes for questions and paragraphs
      resources :questions,:paragraphs

      controller :questions do
        get :cancel_edit_question
        get :remove_paragraph
        get :remove_choice
        get :category_selection,as: "add_question" 
        get :edit_paragraph,as: "admin_materials_question_edit_paragraph"
      end
    end
  end

  # Histories routes
  post "/histories/show_history",to: "histories#show_history"

  # Pusher routes
  get "/pusher_key", to: "application#pusher_key"
  controller :pusher,path: "/pusher" do
    post :auth
    post :webhook
  end

  # Stats routes
#  controller :stats,path: "/stats" do
#    root action: "index", as: "stats"
#    get :show
#    post :pull_pro_bar

#  end

  # Wallposts routes
  controller :wallposts, path: '/wallposts' do
    root action: 'index', as: 'wallposts'
    post :create_wallpost
  end

  resources :wallposts

  # Friendship routes
  post "friendships/add", to: "friendships#add"
  get "friendships/pending_requests", to: "friendships#pending_requests", as: "friend_requests"


  # Root page
  root to: "homepage#index",as: :index

  # Emergency routing
  get ":controller/:action.:format"
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :question
  belongs_to :room_mode
  has_many :questions_buffers
  has_many :questions, through: :questions_buffers
  has_many :users
  has_many :histories
  has_many :objects, class_name: "RecentActivity", as: "object"
  has_many :subjects, class_name: "RecentActivity", as: "subject"

  validates :room_mode_id, presence: true
  attr_accessible :title, :room_mode_id

  # Input: a number indicating some status
  # Return: true if every user in the room has the given status, false otherwise
  def owner
    #owner_array returns an array of 2 elements, the first one is the user_id, second one is number of questions answered in the room
    #if there's no user in the room, in returns []
    owner_array = History.where(
      room_id: self.id, 
      user_id: self.users.collect {|u| u.id}
    ).group(:user_id).count.max
    return User.find(owner_array[0]) if owner_array
  end

  def active_users
    self.users.where("status > (0)")
  end
  def deactivate
    self.update_attribute(:active, false)
  end

  def status_checker(i)
    self.users
        .select(:status)
        .where(:status => [1,2,3])
        .map {|u| u.status==i}
        .inject {|b,a| b and a}
  end
    
  # Return: true if the room is ready to show explanation, false otherwise
  def show_explanation?
    status_checker(2) #Show explanation when everyone is "confirmed" or status==2
  end
    
  def show_next_question?
    status_checker(3) #Show next question when everyone is "ready" or status==3
  end

  def mastered_questions
    return users.collect { |u| u.mastered_questions } 
                .inject { |this,that| this & that }
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_filter :authenticate_user!
  protect_from_forgery except: [:index, :room_list]

  def index
    @name = current_user.name
    @friends = current_user.friends
    @image = current_user.profile.image
    @top_users = User.joins(:profile).order("gp DESC").limit(5)
    @recent_activities = RecentActivity.where(subject_type: "User").where(subject_id: current_user.friend_ids.push(current_user.id)).order("created_at DESC")
    gon.user_id = current_user.id
    @new_room = Room.new
    #current_user.update_attribute(:status,0) unless current_user.status==0

    publish_async("presence-rooms", "update_online_users",{
      name: current_user.name,
      email: current_user.email,
      image: current_user.profile.image
    })
  end

  # Request type: POST
  # Return: the room list
  # Used for dynamically updating the room list
  def room_list
    @rooms = Room.where(active: true)
    render partial: "room_list"
  end

  def create
    @room = Room.new(params[:room])
    if @room.save
      # See application_controller for publish_async method.
      publish_async("presence-rooms", "rooms_change", {})
      redirect_to room_join_path(@room.id)
    else
      alert=""
      @room.errors.full_messages.each { |msg| alert+=msg+"\n" }
        
      redirect_to rooms_path, alert: alert
    end
  end

  def join
    @room = Room.find params[:room_id]
    if @room.active?
      new_activity = current_user.subjects.generate("join_room")
      new_activity.object = @room
      new_activity.save
      current_user.update_attributes({
        room_id: @room.id,
        status: 0
      })
      gon.user_id = current_user.id
      gon.room_id = @room.id
      gon.observing = (@room.users.count!=1)
      choose_question!(@room) if !@room.question
      gon.question_id = @room.question_id
      publish_async("presence-room_#{@room.id}","users_change", {})
      publish_async("presence-rooms", "update_recent_activities", {
        message: "#{current_user.name} has joined room #{@room.title}",
        user_name: current_user.name,
        user_image: current_user.profile.image
      })
    else
      redirect_to rooms_path,alert: "The room you were looking for has been deactivated"
    end

  rescue ActiveRecord::RecordNotFound
    redirect_to rooms_path,alert: "The room you were looking for could not be found."
  end

  # Request type: POST
  # Input params: none
  # Return: HTML of the user list of the room the user is in
  # Used for dynamically updating user list in each room
  def user_list
    @room = current_user.room
    @user_list = @room.users
    render partial: "user_list"
  end
  # Request type: POST
  # Input params: choice_id, room_id
  # Effect: create new history item, choose next question
  # Return: current question's id, next question's id, selected choice's id 
  def confirm
    return unless current_user.status==1
    @room = current_user.room
    @current_question = @room.question
    channel="presence-room_#{@room.id}"
    publish_async(channel, "users_change", {})
    if params[:choice_id]
      @choice_id = params[:choice_id]
      new_history_item = History.create({user_id: current_user.id, room_id: @room.id, question_id: @room.question.id, choice_id: @choice_id})
      publish(channel, "update_histories", {
        history_id: new_history_item.id
      })

      # Consider badges
      badges=BadgeManager.awardBadges(current_user,@current_question,Choice.find(@choice_id))
        # If user received some badge(s), post the news
      unless badges.empty?
        badges.each do |badge|
          news="#{current_user.name} has received #{badge.name} badge. Congratulations!"
          publish_async(channel,"update_news",{
            news: news
          })

          publish_async("presence-rooms", "update_recent_activities", {
            message: news
          })

          message=render_to_string partial: "badges/badge_notification",locals: {badge: badge}
          publish_async("user_#{current_user.id}","notification",{
            title: "Got new badge",
            message: message,
            type: "success"
          })

        end
      end
    end
    
    current_user.update_attribute(:status, 2)
    if @room.show_explanation?
      # Show explanantion
      publish_async(channel, "show_explanation", {})
    end

    render test: "OK", status: "200"
  end
  
  # Request type: POST
  # Input: room_id
  # Effect: change user's status to 3 (Ready). 
  #   If everyone is ready then choose next question and publish_async to /rooms/next_question
  def ready
    return unless current_user.status==2
    @room = current_user.room
    publish_async("presence-room_#{@room.id}","users_change",{})
    current_user.update_attribute(:status, 3)
    if @room.show_next_question?
      if @next_question = choose_question!(@room)
        @room.users.each do |user|
          user.update_attribute(:status, 1)
        end
        question_id = @next_question.id
      else
        question_id = 0
      end

      #Publish next_question
      #If there're questions left, publish question_id
      #Else, publish question_id = 0, it will redirect user out of the room
      publish("presence-room_#{@room.id}","next_question", {
        question_id: question_id
      })
      render text: "OK",status: "200"
    end
  end

  def invite
    publish_async("user_#{params[:user_id]}", "invite", {
      user_id: current_user.id,
      user_name: current_user.name,
      room_id: current_user.room_id
    })

    render text: "OK", status: "200"
  end

  # Request type: GET
  # User quiting the room
  # Note: this is different from kick since it's user clicking the quit button, not closing the window. It's called by the user himself
  def review
    room = Room.find(params[:room_id])
    publish_async("presence-rooms", "update_recent_activities", {
      message: "#{current_user.name} has left room #{room.title}."
    })
    histories = current_user.histories
                                .where(room_id: room.id)
                                .joins(:choice)
                                .includes(:question)
    @questions = histories.collect do |h| {
        id: h.question_id,
        prompt: h.question.prompt,
        paragraph: h.question.paragraph,
        choices: h.question.choices.collect do |c| {
          data: c,
          result: if h.question.correct_choice_ids.include? c.id
                    "correct"
                  elsif c.id==h.choice_id
                    "selected"
                  end
          }
        end
      }
    end
  end

  # Input: question_id
  # Return: JSON of that question
  def show_question
    require "parser"
    current_user.update_attribute(:status, 1)
    publish_async("presence-room_#{current_user.room_id}", "users_change", {})
    if !params[:question_id]
      render json: {
        message: "Sorry, we ran out of questions for you"
      }
    else
      @question = Question.find(params[:question_id])

      # Question contents, to be returned to the ajax requestor
      question_choices=render_to_string(@question.choices).html_safe
      question_prompt=@question.prompt.parse(question_id: @question.id,is_passage: false).html_safe
      paragraph=@question.paragraph ? @question.paragraph.content.parse(question_id: @question.id,is_passage: true).html_safe : ""
      question_image_url=@question.image_file_name!=nil ? @question.image.url : ""

      render json: {
        question_image_url: question_image_url,
        question_prompt: question_prompt,
        question_choices: question_choices,
        paragraph: paragraph
      }
    end
  end

  # Request type: POST
  # Input: choice_id
  # Return: HTML of the explanation for the question in the room the user is in
  def show_explanation
    @room = current_user.room
    @question = @room.question
    return if !@room.show_explanation?
    last_choice = current_user.histories.last.choice if !current_user.histories.empty?
    current_user_choice = (last_choice and last_choice.question_id==@question.id) ? last_choice : nil

    puts "User #{current_user.id} chose #{current_user_choice.id if current_user_choice}"
    @choices = @question.choices.collect do |choice| {
      data: choice,
      result: if choice.correct
                "correct"
              elsif current_user_choice and choice.id==current_user_choice.id
                "selected"
              end,
      selected: @room.active_users.all.select {|u| u.histories.last.choice_id == choice.id if !u.histories.empty?}
    }
    end
    messages = {
      correct: "Congratulations! You got the right answer.",
      incorrect: "Sorry, you got the wrong answer. See explanation below.",
      blank: "You didn't select an answer. See explanation below."
    }
    styles = {
      correct: "alert alert-success",
      incorrect: "alert alert-error",
      blank: "alert"
    }
    # If there's a choice_id (user chose a choice) and that choice is correct
    if current_user.status != 0
      #If user didn't select answer
      if current_user_choice==nil
        @change= current_user.lose_to!(@question)
        @message = messages[:blank]
        @style = styles[:blank]
      #If user chose an incorrect answer
      elsif !current_user_choice.correct?
        @change = current_user.lose_to!(@question)
        @message = messages[:incorrect]
        @style = styles[:incorrect]
      else
        @change = current_user.win_to!(@question)
        @message = messages[:correct]
        @style = styles[:correct]
      end
    end
    render partial: "show_explanation"
  end

  # Request type: POST
  # Returns a message to put in a chat box
  def chat_message
    @room=current_user.room

    @chat_message=ChatMessage.create! content: params[:message],owner_id: current_user.id
    chat_message=render_to_string partial: "chat_message/chat_message"

    publish_async("presence-room_#{@room.id}", "chat_message", {

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.haml
= form_for (@new_room) do |f|
  - if @new_room.errors.any?
    %ul
      - @new_room.errors.full_messages.each do |msg|
        %li=msg

  %div.control-group.text-center
    = f.label :title, "Room title"
    = f.text_field :title
  %div.control-group.text-center
    = f.label :room_mode_id, "Room mode"
    = f.select(:room_mode_id, RoomMode.all.collect { |m| [m.title, m.id]})
  %div.text-center
    = f.submit class:"btn btn-primary"

app/views/rooms/_friend_list.html.haml
%div.myhead
  %div.row-fluid
    %div.span6
      %h3 Friends
%div.mousescroll
  %ul.nav.nav-tabs.nav-stacked
    - friends.each do |f|
      %li
        %a{href: user_profile_path(f)}
          =image_tag(f.profile.image)
          = f.name
          - if f.room_id!=0
            is in room #{f.room_id}
:javascript
  $(".mousescroll").slimscroll({
    color: '#666',
    size: '10px',
    height: '150px'
  });

app/views/rooms/_left_side_bar.html.haml
%div.span3
  %div#profile
    %div.row-fluid
      %table.table.table-bordered
        %tbody
          %tr
            %td{:colspan => '3'}
              %div.span4
                - if current_user.profile.image
                  = image_tag(current_user.profile.image, class: "profile-pic")
              %div.span8
                %h3= current_user.name
                %small= link_to "View my profile","/users/#{current_user.id}/profile"
          %tr
            %td 
              %strong #{current_user.gp}
              %small GP
            %td 
              %strong #{current_user.level}
              %small Level
          %tr
            %td
              %strong #{current_user.reputation}
              %small Reputation
            %td 
              %strong #{current_user.rank}
              %small Rank
  
  %div.separator

  %div.bordered-container#ranking
    %div.myhead
      %h3 Ranking
    %div
      %table.table
        %thead
        %tbody
          - top_users.each do |user|
            %tr
              %td.row-fluid.user_component
                %div.span5.row-fluid
                  %div.span4
                    %h2= "##{user.rank}"
                  %div.span8
                    = image_tag(user.profile.image,:class => "profile-pic")
                %div.span7
                  %a{href:"/users/#{user.id}/profile"}
                    %h4= user.name
                  %div.user-stats.row-fluid
                    %div.span2
                      %i.icon-star-empty
                    %div.span8
                      %p= "GP #{user.gp}"

app/views/rooms/_recent_activity.html.haml
%div.activity.row-fluid
  %div.span2
    =image_tag(a.subject.profile.image, class: "profile-pic")
  %div.span9
    %div.row-fluid
      %strong= a.subject.name
    %div.row-fluid.spacing.activity-messages
      %p= a.render

app/views/rooms/_right_side_bar.html.haml
%div.span4
  %div.bordered-container#recent_activities
    %div.myhead
      %h3 Recent Activities
    %div.pre-scrollable
      %div#activities_list
        - @recent_activities.each do |a|
          = render "recent_activity", a: a

  

app/views/rooms/_room_item.html.haml
%div.accordion-group{id: "room_#{room.id}"}
  %div.accordion-heading
    %div.accordion-toggle{"data-toggle" => "collapse", "data-target" => "#body-room_#{room.id}", "data-parent" => "#room_list"}
      %div.row-fluid
        %div.span2.profile_image
          - if room.owner and room.owner.profile.image
            =image_tag(room.owner.profile.image)
        %div.span8
          %h3.room-title=room.title
          %span.label.label-success.room-mode= room.room_mode.title
        %div.span2
          %small= time_ago_in_words(room.created_at) + " ago"
  %div.accordion-body.collapse{id: "body-room_#{room.id}"}
    %div.accordion-inner.row-fluid
      %div.span2
        %strong Players
      %div.span6
        - room.users.each do |user|
          %a{:href => "#", :rel => "tooltip", "data-original-title"=>"#{user.name}"}
            =image_tag user.profile.image, :class => "profile-pic-small"
      %div.span2
      %div.span2
        = link_to "Join", room_join_path(room.id), {class: "btn btn-primary"}

app/views/rooms/_room_list.html.haml
%div.myhead
  %div.row-fluid
    %div.span6
      %h3 Room list
    %div.span6
      %button.btn.btn-primary{"data-toggle"=>"modal", "href"=>"#new_room"}New room
%div.room-list-body.pre-scrollable
  - if @rooms.empty?
    %div.accordion-group.text-center
      %div
        %p No one's around. Create your own room!
  - @rooms.each do |room|
    = render "room_item", room: room

app/views/rooms/_search_more_results_link.html.haml
%div
  = link_to "See more results for #@term",search_friends_path(term: @term)
  %br
  %small "Displaying top 8 results"

app/views/rooms/_show_explanation.html.haml
%div.row-fluid{class: @style}
  %p= @message

- @choices.each do |choice|
  %div.row-fluid.btn.each_choice.disabled{id: choice[:data].id.to_s,class: choice[:result] }
    %div.span2.choice_letter= choice[:data].choice_letter
    %div.span8.choice_content
      %div
        = choice[:data].content.parse_latex.html_safe
      %div.selected_users
        - choice[:selected].each do |user|
          = image_tag user.profile.image, {"rel" => "tooltip", "data-original-title"=> user.name }

:javascript
  $(".correct").addClass("btn-success")
               .append("<div class='span2'><i class='icon-ok icon-white' /></div>")
  $(".selected").addClass("btn-danger")
  $(".selected_users img").tooltip()

app/views/rooms/_top_users.html.haml
%div
  %table.table
    %thead
      %tr
        %th Name
        %th Exp
    %tbody
      - top_users.each do |u|
        %tr
          %td= u.name
          %td= u.exp

app/views/rooms/_user_list.html.haml
%table.table.table-condensed
  %tbody
    - @user_list.each do |user|
      %tr
        %td.row-fluid.user_component.well
          = render user

app/views/rooms/index.html.haml
%div.row-fluid#rooms_index
  = render "left_side_bar", top_users: @top_users
  %div.span5
    %div.accordion#room_list

    %div.bordered-container
      %div.online-users-head
        %h4 Online Users
      %div.online-users-body
        %div.online-users-container
      %div.friends-head
        %h4 Friends
      %div.friends-body
        %div.friends-container
          -current_user.friends.each do |f|
            = image_tag f.profile.image, :class => "profile-pic"         

    %br
    %div.modal.hide#new_room
      %div.modal-header
        %button.close{"type" => "button", "data-dismiss" => "modal"}x
        %h3 Create new room
      %div.modal-body
        =render "new"
    %div.modal.hide#invitation
      %div.modal-header
        %button.close{"type" => "button", "data-dismiss" => "modal"}x
        %h3 You're invited!
      %div.modal-body
        %p
      %div.modal-footer
        %button.btn{"data-dismiss"=>"modal"}Decline
        %button.btn.btn-primary#accept Accept

  = render "right_side_bar"

app/views/rooms/join.html.haml
%div.row-fluid.room_settings
  %div.span8
    %h2#room_tite
      = "Room #{@room.title}"
      %small#room_mode=  @room.room_mode.title
  %div.span1
    %div#timer.pull-right{display: "inline"}
  %div.span3
    %div.row-fluid
      %div.span9
        %button.btn.btn-danger#quit
          Quit
      %div.span3.pull-right
        %div
          %button.btn.btn-primary#invite_button Invite

%div.row-fluid#rooms_join
  %div.span9
    %div.row-fluid.question_active#current_question
      %div.span6#paragraph.prettyprint.pre-scrollable.linenums
      %div.span6#question_container
        %div.question_image
        %div.prompt_container
          %h4 Question
          %div.row-fluid
            %div.span2
            %div.span10
              %p.lead#prompt
      %div.span6
        %h4 Choices
        %div.row-fluid
          %div.span2
          %div.span8
            %div#choices
            %div.pull-right.control
              %button.btn.btn-primary#confirm{style: "display:none"} Confirm
              %button.btn.btn-primary#ready{style: "display:none"} Ready
  %div.span3
    %div#top_nav
      %div#user_list
    %div#bottom_nav
      %ul.nav.nav-tabs
        %li.active
          %a{"href" => "#chat", "data-toggle" => "tab"}Chat
        %li
          %a{"href" => "#history", "data-toggle" => "tab"}History
      %div.tab-content
        %div.tab-pane.active#chat
          %div.chat-content.pre-scrollable
          
          = label_tag :message
          %div.row-fluid
            %div.span12
              = text_area_tag :message,"",{class: "chat_message span12"}
          
          = submit_tag "Send",class: "btn btn-primary chat_send"
        %div.tab-pane#history.pre-scrollable
%div.modals-container
  %div.modal.hide#observing{reload: @reload}
    %div.modal-header
      %h3 Waiting...
    %div.modal-body
      %p Please wait for the next round to begin
    %div.modal-footer
      = link_to "Go back to room list", rooms_path, {class: "btn btn-primary"}

  %div.modal.hide#quit_modal{reload: @reload}
    %div.modal-header
      %h3 Quit room
    %div.modal-body
      %p Are you sure you want to quit?
    %div.modal-footer
      =link_to "Yes, take me to the review page", room_review_path(@room.id), {class: "btn btn-primary"}
      =link_to "Yes, take me to the room list", rooms_path, {class: "btn btn-primary"}
      %a.btn{"href" =>"#", "data-dismiss" => "modal"} No

  %div.modal.hide#invite
    %div.modal-header
      %h3 Invite people to the room
    %div.modal-body
      %p
    %div.modal-footer
      %a.btn{"href" =>"#", "data-dismiss" => "modal"} Cancel

app/views/rooms/search_friend_all_results.html.haml
%div.row-fluid#rooms_search
  = render "left_side_bar"
  %h2 All Results
  %div.span6
    - @users.each do |user|
      = render partial: "users/user_item",locals: {user: user}

  = render "right_side_bar",top_users: @top_users